spring.application.name=animecom

spring.datasource.url=jdbc:postgresql://ep-mute-smoke-adthh8m9.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

